import JoinOrgCard from "@/app/components/ui/general/join-org-card";

const mockOrgs = [
  {
    title: "ICPEP",
    orgID: "icpep",
    subtitle: "Institute of Computer Engineers of the Philippines",
    tagText: "Engineering",
    memberCount: 120,
    eventCount: 8,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "JPIA",
    orgID: "jpia",
    subtitle: "Junior Philippine Institute of Accountants",
    tagText: "Accounting",
    memberCount: 95,
    eventCount: 5,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "CES",
    orgID: "ces",
    subtitle: "Civil Engineering Society",
    tagText: "Engineering",
    memberCount: 80,
    eventCount: 3,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP Math Club",
    orgID: "upmath",
    subtitle: "University of the Philippines Mathematics Club",
    tagText: "Mathematics",
    memberCount: 60,
    eventCount: 4,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP Physics Society",
    orgID: "upphys",
    subtitle: "University of the Philippines Physics Society",
    tagText: "Physics",
    memberCount: 50,
    eventCount: 2,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP Chem Circle",
    orgID: "upchem",
    subtitle: "University of the Philippines Chemistry Circle",
    tagText: "Chemistry",
    memberCount: 70,
    eventCount: 6,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP BioSoc",
    orgID: "upbio",
    subtitle: "University of the Philippines Biological Society",
    tagText: "Biology",
    memberCount: 55,
    eventCount: 3,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP English Club",
    orgID: "upeng",
    subtitle: "University of the Philippines English Club",
    tagText: "Literature",
    memberCount: 40,
    eventCount: 2,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
  {
    title: "UP Debate Society",
    orgID: "updebate",
    subtitle: "University of the Philippines Debate Society",
    tagText: "Debate",
    memberCount: 30,
    eventCount: 5,
    avatarUrl: undefined,
    coverPhotoUrl: undefined,
  },
];

export default function OrgOversightPage() {
  return <JoinOrgCard orgs={mockOrgs} />;
}
