alter table "public"."broadcast" add column "id" bigint generated by default as identity not null;

alter table "public"."broadcast" enable row level security;

CREATE UNIQUE INDEX broadcast_pkey ON public.broadcast USING btree (id);

alter table "public"."broadcast" add constraint "broadcast_pkey" PRIMARY KEY using index "broadcast_pkey";

create policy "Users can view relevant broadcasts from their university"
on "public"."broadcast"
as permissive
for select
to public
using (((universityid = ( SELECT s.universityid
   FROM student s
  WHERE (s.user_id = auth.uid())
 LIMIT 1)) AND ((recipient = 'all'::text) OR (recipient = 'students'::text) OR ((recipient = 'organizations'::text) AND (EXISTS ( SELECT 1
   FROM orgmember om
  WHERE (om.studentid = ( SELECT s.studentid
           FROM student s
          WHERE (s.user_id = auth.uid())
         LIMIT 1))))))));



